### ISSUE TITLE
Problemas na homologação.

### ISSUE THREAD

**Issue by upmauro** [thiagosm/pyboleto#1]
·         Nosso número: apresentar formato XYNNNNNNNNNNNNNNN-D (17 + DV).
·         Alterar campo "Espécie" para "Espécie Moeda" ;
·         Alterar campo "Descontos/Abatimentos" para "Desconto" ;
·         Alterar campo "Outras deduções" para "Outras Deduções/Abatimento" ;

**Comment by thiagosm** [comment]
Esse formato numeração é padrão sigcb da caixa. Utilizar variável início nosso número, 14,21,24 etc. Atualmente não tive problemas com o modelo sigcb, o código é usado na geração de mais de 50 mil boletos por mês.
