### ISSUE TITLE
Problema com o layout

### ISSUE THREAD

**Issue by renanpalmeira** [thiagosm/pyboleto#2]
No banco do Itaú, o layout atual não esta sendo aceito, isso só esta acontecendo comigo?

**Comment by thiagosm** [comment]
Emito boleto todo dia carteira 157. Até o momento não tive problemas. Qual carteira tá usando e qual versão do pyboleto desse source tá usando?

**Comment by renanpalmeira** [comment]
To usando a carteira 109, e a versão do pyboleto é 0.2.14

**Comment by thiagosm** [comment]
Já tá Na versão 0.2.19.
pip install git+https://github.com/thiagosm/pyboleto.git

Posso ver se tenho clientes usando carteira 109, pois os que eu conheço usam 157.

**Comment by thiagosm** [comment]
Esse modelo não usa 15 dígitos. Taçve

**Comment by thiagosm** [comment]
Talvez o modelo 109 usa 15 dígitos e aí será necessário olhar na documentacao para adaptar

**Comment by renanpalmeira** [comment]
no caso, acabei de atualizar, o layout "from pyboleto.pdf import BoletoPDF" continua não batendo com o exemplo que o gerente me passou

**Comment by thiagosm** [comment]
Se quiser adicionar aí no gtalk opencode@gmail.com e me passa como o gerente quer que eu posso ver o que muda no source.

**Comment by renanpalmeira** [comment]
blz, vou te encaminhar um print por email mesmo, pode ser?

**Comment by thiagosm** [comment]
Pode sim

**Comment by renanpalmeira** [comment]
mandei o email já, outra duvida q estou tendo é se teria alguma forma de adicionar um cabeçaria do Boleto pdf, eu tentei porém um elemento fica em cima do outro
