### ISSUE TITLE
Fork oficial do pyboleto

### ISSUE THREAD

**Issue by rafaelreuber** [thiagosm/pyboleto#5]
Sabemos que o o repositório oficial do pyboleto eduardocereto está a muito tempo sem atualização. Submeti um pull request para atualizar a logomarca do banco Santander em março de 2017 e até agora ele não foi avaliadado. Existem várias coisas que precisam ser feitas no pyboleto. Acho que o colega eduardocereto perdeu um interesse de manter o projeto ou por razões pessoais, simplemente ele não pode fazê-lo.

O você tem interesse de criar um novo fork, inclusive com outro nome, do pyboleto? O que acha?

**Comment by rafaelreuber** [comment]
Olá, thiago, o que acha disso?

**Comment by thiagosm** [comment]
Por mim sem problema jovem. Eu mantive esse porque atendemos mais de 500 empresas com diferentes tipos de cobrança e com boleto de arrecadação também, então para não depender dos outros foi criado fork e eu mesmo mantenho ele.
